Changes with this submission:
51: Enhance EnumerationIterator IF to indicate iterator is already filtered.
52: Enumeration Pull may return zero objects when filtered.
53: Concurrent access to Enum context not protected

In addition the following items have been added:

1. EnumerationSupport, EnumerationHandler and EnumerationIterator have been
   completely reworked and simplified. An IteratorFactory interface has
   been added. Users wanting EnumerationSupport to handle their enumeration
   requests will need to port their iterator to the new EnumerationIterator
   interface, create an IteratorFactory and register their factory with
   EnumerationSupport.

   EnumerationSupport & EnumerationHandler are now able to support concurrent
   requests to a single resource URI.

   EnumerationSupport will now correctly detect "projections" in the filter
   and wrap the projected items within an XmlFragment. Projections are selections
   of a portion of a resource as opposed to the whole resource.

   EnumerationSupport will not filter or wrap in XmlFragment items returned from
   an iterator that returns true from EnumerationIterator.isFilter().

   The test User handler EnuerationUserHandler has been completely rewritten
   to now use the EnumerationSupport & is now split into UserEnumerationHandler,
   UserIteratorFactory & UserStore. They are used for testing and can be used
   as an example.

2. A filter unit test has been added. Several bugs were fixed in this area
   due to errors produced by this test. In particular, a namespace map was
   needed to be added to the client interfaces accepting a filter. This map
   contains the namespaces used in the filter expression. The namespaces are
   needed on the server side in order to properly evaluate the filter.
   Previously the namespaces for the document produced on the server side were
   passed to the XPath object. This was incorrect.

   Additionally NamespaceMap(Node node) was used on the server side to obtain
   the set of namespaces. This scanned the document from the specified node
   to the last child. This was incorrect. It needed to scan the document from
   the specified node to the root (opposite direction).

   Several support functions were added to process filtering on the server side.
   See below in item 3.

3. Several client and server interfaces have been enhanced to allow for easier
   handling of XmlFragment and filtering in general.
   EnumerationSupport has already been mentioned.

   EnumerationSupport has the added method:
   public static Filter createFilter(final Enumeration request)
   for easy creation of a Filter object from an Enumeration Request.
   EventingSupport & TransferExtensions have similar methods.

   BaseSupport has added two methods, createXmlFragment(List<Node>) &
   createXmlFragment(Nodelist) to ease creation of XmlFragment objects.
   TransferExtensions has done the same for use on the client side.

   The Filter interface was changed to return the filtered object as
   a Nodelist object rather than just a boolean. The Nodelist may contain
   projected elements if the filter contains a projection. The Nodelist
   can be diretly passed to BaseSupport.createXmlFragment(Nodelist)
   described above.

   Transfer.getResource(QName name) was added to easily get the resource object
   passed in Create, Update, & Delete requests.

   TransferExtensions.getResource(QName) overrides Transfer.getResource() and
   will check for XmlFragment objects if the QName object is not found.

   TransferExtensions.setFragmentGetResponse(
			final SOAPHeaderElement fragmentTransferHeader,
			final Object resource)

   has been added. This method will, using any registerd Filter handler,
   process the Fragment Transfer get against the provided resource object
   and set the result in the response. The resulting resource will
   automatically be wrapped into an XmlFragment for the caller and placed
   into the body of the repsonse. NOTE: results from applying the
   Fragment Transfer filter are always warpped in an XmlFragment by
   this method, whether the filter specified projections or not, as the caller
   specifically requested Fragment Transfer. This is not done for
   enumerations where the fragment transfer is mixed in with the wsman:filter.
   In the case of Enumerations if the filter selects the entire resource
   it is not wrapped in an XmlFragment.

   If setFragmentGetResponse() is called with fragmentTransferHeader set
   to null the method will simply put the resource object into the body of
   the response for the caller.

   NOTE: More work is needed on the client side to make, so I have not
         listed or closed issue #24: Client fragment support should be simplified

4. To run the tests the "se/src/binding.properties" file MUST be edited first.
   Uncomment the line:

   com.sun.ws.management.xml.custom.packagenames = foo.test,com.hp.examples.ws.wsman.user

   This is needed for some tests to correctly execute.

5. I could NOT correctly build the JAXB Object Factory sources using the build.xml.
   All sources were built and compiled OK, but some tests failed. The reason is that
   attempts to add the "mustUnderstand" attribute to a header did not work. The
   call did not produce an error, but the header did not have the attribute. I
   duplicated this problem on two different system. Eventually I used the source
   that was previously built with JAXB and the tests then passed. The following was
   the test that failed:


    [junit] Testsuite: management.ManagementTest
    [junit] Tests run: 6, Failures: 1, Errors: 0, Time elapsed: 4.296 sec

    [junit] Testcase: testValidate(management.ManagementTest):  FAILED
    [junit] expected:<3> but was:<0>
    [junit] junit.framework.AssertionFailedError: expected:<3> but was:<0>
    [junit]     at management.ManagementTest.testValidate(ManagementTest.java:275)

6. testMaxEnvelopeSizeTooBig() fails for test-jaxws. I do not know why. It is the
   only test that failed for me, though. I commented it out for my tests.